### ISSUE TITLE
mlr3 v0.4.0 breaks PDPs

### ISSUE THREAD

**Issue by giuseppec** [christophM/iml#138]
Last week the following code worked with mlr3 v0.3.0 and now it breaks. Apparently PDP for numeric features are not possible anymore?

```r
library("mlr3")
library("mlr3learners")
library("iml")

credit.task = tsk("german_credit")
lrn = lrn("classif.ranger", predict_type = "prob")

set.seed(123)
model = lrn$train(credit.task)
data = credit.task$data()
iml = Predictor$new(model, data = data, y = "credit_risk", type = "prob")
pdp = FeatureEffects$new(iml, feature = "duration", method = "pdp+ice")
plot(pdp) 

#Fehler: Incompatible types during auto-converting column 'duration': failed to convert from class 'numeric' to class 'integer'
```

**Comment by giuseppec** [comment]
Closing here as this is rather an issue in mlr3, see https://github.com/mlr-org/mlr3/issues/533
